#!/bin/bash
echo '------------------Check CNV------------------------------------------------'

if [ $# -lt 2 ]; then

        echo 'Usage: 0 <Proj_Dir> <Tsample> '
            exit
fi
proj_dir=$1
t_sample=$2
IFS_OLD=$IFS

IFS='

'

cnv=`cat /biocluster/data/biobk/user_test/lipidong/work/check_cnv/bed.xls`
#PC290TQ1.exome.cnvTable.temp

if [ -f cnv.txt ];then
    rm cnv.txt
fi

for ii in $cnv;do
    chr=`echo $ii| awk '{print $1}'`
    start=`echo $ii | awk '{print $2}'`
    end=`echo $ii|awk '{print $3}'`
    echo $ii
    echo $ii >> ${proj_dir}/cnv.txt
    #echo "le ./*.mutect.SNP.vcf | grep '^[^#]'|awk '{if(\$1==${chr} && \$2>=${start} && \$2<=${end}) print \$10\"\t\"\$11 }'"
    cmd="less -SN ./*.mutect.SNP.vcf | grep '^[^#]'|awk '{if(\$1==${chr} && \$2>=${start} && \$2<=${end}) print \$10\":\"\$11 }' | awk -F':' '{ if(( (\$1==0 && (\$5<=0.7 && \$5>=0.4)) ||  (\$1==\"0/1\" && (\$10<=0.7 && \$10>=0.4)) )  && (\$9>100 && \$4>100) ) print \$0 }' >> ${proj_dir}/${t_sample}_cnv.txt"
    echo $cmd
    echo '################################################################' >> cnv.txt
    eval $cmd
    echo ''
done
echo 'cnv was written to cnv.txt'
IFS=$IFS_OLD
#awk '{if($9>0.5) print "le ./02_var/*.mutect.SNP.vcf | grep \'^[^#]\'|awk \'{if($1==" $1" && \$2>="$2 " && \$2<="$3")  print \$10\"\t\"\$11 }" }'


echo ''
echo ''

